### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by hajix** [kuaikuaikim/DFace#18]
Hi
I run test_image.py and get the following error:

> /home/aj/repo/DFace/dface/core/models.py:8: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(m.weight.data)
/home/aj/repo/DFace/dface/core/models.py:9: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(m.bias, 0.1)
Traceback (most recent call last):
  File "test_image.py", line 18, in <module>
    bboxs, landmarks = mtcnn_detector.detect_face(img)
  File "/home/aj/repo/DFace/dface/core/detect.py", line 622, in detect_face
    boxes, boxes_align = self.detect_rnet(img, boxes_align)
  File "/home/aj/repo/DFace/dface/core/detect.py", line 391, in detect_rnet
    tmp = np.zeros((tmph[i], tmpw[i], 3), dtype=np.uint8)
ValueError: negative dimensions are not allowed

**Comment by kuaikuaikim** [comment]
@hajix please use python2.7 and the pytorch version less than 0.3, i did not test for python3 before.

**Comment by thnkim** [comment]
@kuaikuaikim Hello, I have the same issue although I tried it using python 2.7.15 and pytorch 0.2.0+0b92e5c.

**Comment by rohith14** [comment]
@kuaikuaikim  and @hajix :  I am running into the same issue.  Any update?  Thanks

**Comment by yangjian940712** [comment]
Recently, I also encountered the same problem. I compared it with the tensorflow version of mtnnn.I found that there is a problem in the preprocessing of the network. The image needs to be multiplied by 1/255, but Dface is not. When you test, go to view and confirm the input image tensor @kuaikuaikim @hajix

**Comment by educob** [comment]
It didn't work for me.

I went to detect.py and changed:
```
def detect_rnet(self, im, dets):
        im = im * 1/255
```

But I still get the error.

Where should I make the changes?

Thanks.

**Comment by AngelaDevHao** [comment]
> Recently, I also encountered the same problem. I compared it with the tensorflow version of mtnnn.I found that there is a problem in the preprocessing of the network. The image needs to be multiplied by 1/255, but Dface is not. When you test, go to view and confirm the input image tensor @kuaikuaikim @hajix

Did you run the demo successfully? I found the reg output by PNet are too large, which results this error. I try to add the 1/255 preprocess, but it didn't work. Do you have some advice? @kuaikuaikim @hanson-young

**Comment by leadcain** [comment]
remove python2.7 pickle

redefine pickle as below:
     import six; from six.moves import cPickle as pickle

and modify the code as below:
   with open(det_boxs_file, "rb") as file:
      det_boxes = pickle.Unpickler(file).load()
