### ISSUE TITLE
Train pnet error

### ISSUE THREAD

**Issue by CaptainEven** [kuaikuaikim/DFace#20]
.\dface\core\models.py:9: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(m.bias, 0.1)
Traceback (most recent call last):
  File "g:/mtcnn/dface/train_net/train_p_net.py", line 92, in <module>
    use_cuda=args.use_cuda)
  File "g:/mtcnn/dface/train_net/train_p_net.py", line 30, in train_net
    use_cuda=use_cuda)
  File ".\dface\train_net\train.py", line 92, in train_pnet
    show1 = accuracy.data.tolist()[0]
TypeError: 'float' object is not subscriptable

**Comment by lijie2160** [comment]
同样的问题，请问你的解决了吗？

**Comment by qiantanzhijiao** [comment]
Got it?

**Comment by Dawnlnz** [comment]
I had the same problem. Have you solved it?
