### ISSUE TITLE
Runtime error:zero-dimensional tensor(at position 0) cannot be contatenated

### ISSUE THREAD

**Issue by Llq201809** [kuaikuaikim/DFace#27]
when I run train_p_net.py ,it shows these error:
Traceback (most recent call last):
  File "dface/train_net/train_p_net.py", line 50, in <module>
    end_epoch=args.end_epoch, frequent=args.frequent, lr=args.lr, batch_size=args.batch_size, use_cuda=args.use_cuda)
  File "dface/train_net/train_p_net.py", line 17, in train_net
    train_pnet(model_store_path=model_store_path, end_epoch=end_epoch, imdb=gt_imdb, batch_size=batch_size, frequent=frequent, base_lr=lr, use_cuda=use_cuda)
  File "/home/li/DFace/dface/train_net/train.py", line 97, in train_pnet
    accuracy_avg = torch.mean(torch.cat(accuracy_list))
RuntimeError: zero-dimensional tensor (at position 0) cannot be concatenated

**Comment by Dawnlnz** [comment]
Hello, I have the same problem.Have you saved it?

**Comment by Dawnlnz** [comment]
Thank,I have solved it.

**Comment by markson14** [comment]
change the error line into `accuracy_avg = torch.mean(torch.stack(accuracy_list, dim=0))`
