### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'map'

### ISSUE THREAD

**Issue by Llq201809** [kuaikuaikim/DFace#29]
When I run  gen_Rnet_train_data.py, I meet this problem.

Traceback (most recent call last):
File " dface/ prepare. _data/gen_ Rnet_ train_ data.py", line 216, in <nodule>
gen_ rnet_ data( args. traindata_ store, args . annotation_ file, args . pnet_ model_ file, args.prefix_ path, args.use cuda 
File "dface/prepare data/gen_ Rnet_ train_ data.py", line 61, in gen_ rnet data
gen_ rnet_ sample_ data(data_ dir , anno. file , save file ,prefix_ path)
File "dface/prepare data/gen_ Rnet_ train_ data.py", line 95, in gen. rnet sample data
boxes . np. array(boxes, dtype=np. float32).reshape(-1, 4)
TypeError: float() argunent nust be a string or a nunber, not 'map'1iat . InEo

**Comment by mxs30443** [comment]
I meet the same problem, I fix this problem by change "boxes . np. array(boxes, dtype=np. float32).reshape(-1, 4)" to "boxes . np. array(list(boxes), dtype=np. float32).reshape(-1, 4)"

**Comment by Llq201809** [comment]
Thank you!👍------------------ 原始邮件 ------------------
发件人: "Xiangshen M"<notifications@github.com>
发送时间: 2019年5月17日(星期五) 晚上8:05
收件人: "kuaikuaikim/DFace"<DFace@noreply.github.com>;
抄送: "Llq201809"<2996816323@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kuaikuaikim/DFace] TypeError: float() argument must be a stringor a number, not 'map' (#29)



I meet the same problem, I fix this problem by change "boxes . np. array(boxes, dtype=np. float32).reshape(-1, 4)" to "boxes . np. array(list(boxes), dtype=np. float32).reshape(-1, 4)"
 
&mdash;
