### ISSUE TITLE
TypeError in gen_Pnet_train_data.py

### ISSUE THREAD

**Issue by ltrottier** [kuaikuaikim/DFace#8]
```
12880 pics in total
Traceback (most recent call last):
  File "dface/prepare_data/gen_Pnet_train_data.py", line 175, in <module>
    gen_pnet_data(args.traindata_store,args.annotation_file,args.prefix_path)
  File "dface/prepare_data/gen_Pnet_train_data.py", line 133, in gen_pnet_data
    cropped_im = img[ny1 : ny2, nx1 : nx2, :]
TypeError: slice indices must be integers or None or have an __index__ method
```
The problem is that the n** are not int. Is it safe to simply do:
```
cropped_im = img[int(ny1) : int(ny2), int(nx1) : int(nx2), :]
```
?
I'm using python 3.6

**Comment by kuaikuaikim** [comment]
@ltrottier please try python2.7, dface is not full test on python 3.6.

**Comment by leadcain** [comment]
in gen_Pnet_train_data.py

lien 133 > 
original : cropped_im = img[nx: ny2, nx1, nx2, :] 
modify  : cropped_im = img[(int)nx: (int)ny2, (int)nx1, (int)nx2, :]
